[package]
name = "fortivo-vault"
version = "0.1.0"
edition = "2024"

[features]
logging = [
	"dep:env_logger",
	"libfortivo/logging"
]

[dependencies]
libfortivo = { path = "../libfortivo" }
env_logger = { version = "0.11.8", optional = true }