name: Rust CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4
    - name: Check workspace members
      run: cargo check --workspace --all-features --verbose
    - name: Test workspace members
      run: cargo test --workspace --all-features --verbose
