name: Rust CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4
    - name: Check source
      run: cargo check --verbose
      
  cargo-test:
    runs-on: ubuntu-latest
    needs: cargo-check

    steps:
    - name: Checkout source
      uses: actions/checkout@v4
    - name: Test source
      run: cargo test --verbose
